version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
    pre_build:
        commands:
            # 登入 ECR
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 148761646404.dkr.ecr.us-east-1.amazonaws.com
    build:
        commands:
            - echo Build started on `date`
            - npm install
            - echo npm install completed on `date`
            - npm run build
            - echo npm run build completed on `date`
            # 获取当前时间作为标签
            - TAG=`date "+%Y%m%d%H%M%S"`
            # 构建镜像，镜像名设置为 ECR 中的名字
            - docker build -t 148761646404.dkr.ecr.us-east-1.amazonaws.com/cicdyuanma-app:$TAG ./
            - echo Docker build completed on `date`
            # 推送镜像到 ECR
            - docker push 148761646404.dkr.ecr.us-east-1.amazonaws.com/cicdyuanma-app:$TAG
            - echo Docker push completed on `date`
    post_build:
        commands:
            - echo Build completed on `date`
            # 创建 imagedefinitions.json 文件，包含容器名称和镜像 URL
            - printf '[{"name":"mynginx","imageUri":"%s"}]' 148761646404.dkr.ecr.us-east-1.amazonaws.com/cicdyuanma-app:$TAG > imagedefinitions.json
            - cat imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json